
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/alecthomas/chroma"
  version = "0.2.0"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/gostores/ace"

[[constraint]]
  branch = "master"
  name = "github.com/gostores/amber"

[[constraint]]
  branch = "master"
  name = "github.com/gostores/assert"

[[constraint]]
  branch = "master"
  name = "github.com/gostores/assist"

[[constraint]]
  branch = "master"
  name = "github.com/gostores/configurator"

[[constraint]]
  branch = "master"
  name = "github.com/gostores/cssmin"

[[constraint]]
  branch = "master"
  name = "github.com/gostores/emoji"

[[constraint]]
  name = "github.com/gostores/encoding"
  version = "0.0.1"

[[constraint]]
  branch = "master"
  name = "github.com/gostores/fsintra"

[[constraint]]
  name = "github.com/gostores/fsnotify"
  version = "1.4.2"

[[constraint]]
  branch = "master"
  name = "github.com/gostores/fsync"

[[constraint]]
  branch = "master"
  name = "github.com/gostores/gitmap"

[[constraint]]
  branch = "master"
  name = "github.com/gostores/goman"

[[constraint]]
  branch = "master"
  name = "github.com/gostores/goorgeous"

[[constraint]]
  branch = "master"
  name = "github.com/gostores/inflect"

[[constraint]]
  branch = "master"
  name = "github.com/gostores/leaktest"

[[constraint]]
  branch = "master"
  name = "github.com/gostores/mapstructure"

[[constraint]]
  branch = "master"
  name = "github.com/gostores/mmark"

[[constraint]]
  branch = "master"
  name = "github.com/gostores/notepad"

[[constraint]]
  branch = "master"
  name = "github.com/gostores/osext"

[[constraint]]
  name = "github.com/gostores/pflag"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/gostores/purell"

[[constraint]]
  branch = "master"
  name = "github.com/gostores/require"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-immutable-radix"

[[constraint]]
  name = "github.com/jdkato/prose"
  version = "1.1.0"

[[constraint]]
  name = "github.com/nicksnyder/go-i18n"
  version = "1.10.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/image"

[[constraint]]
  branch = "master"
  name = "golang.org/x/text"
